### ISSUE TITLE
npm ERR! Invalid dependency type requested: alias

### ISSUE THREAD

**Issue by Alex1990** [Alex1990/obito#8]
The console output:

```
npm ERR! Invalid dependency type requested: alias

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ac/.npm/_logs/2019-10-29T03_24_38_281Z-debug.log
npm install error
```

The `/Users/ac/.npm/_logs/2019-10-29T03_24_38_281Z-debug.log` file content:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/ac/.nvm/versions/node/v10.15.3/bin/node',
1 verbose cli   '/Users/ac/.nvm/versions/node/v10.15.3/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '--prefix',
1 verbose cli   '/Users/ac/obito',
1 verbose cli   '@sentry/browser-5.7.0@npm:@sentry/browser@5.7.0' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose npm-session 2d8087b6a629c381
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for @sentry/browser-5.7.0@npm:@sentry/browser@5.7.0 Invalid dependency type requested: alias
8 timing stage:rollbackFailedOptional Completed in 7ms
9 timing stage:runTopLevelLifecycles Completed in 104ms
10 verbose stack Error: Invalid dependency type requested: alias
10 verbose stack     at getFetcher (/Users/ac/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/pacote/lib/fetch.js:68:15)
10 verbose stack     at manifest (/Users/ac/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/pacote/lib/fetch.js:15:19)
10 verbose stack     at pinflight (/Users/ac/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/pacote/manifest.js:24:12)
10 verbose stack     at /Users/ac/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:29:24
10 verbose stack     at Promise._execute (/Users/ac/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/bluebird/js/release/debuggability.js:303:9)
10 verbose stack     at Promise._resolveFromExecutor (/Users/ac/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:483:18)
10 verbose stack     at new Promise (/Users/ac/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:79:10)
10 verbose stack     at _inflight (/Users/ac/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:28:25)
10 verbose stack     at /Users/ac/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:22:14
10 verbose stack     at tryCatcher (/Users/ac/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
10 verbose stack     at Promise._settlePromiseFromHandler (/Users/ac/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
10 verbose stack     at Promise._settlePromise (/Users/ac/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
10 verbose stack     at Promise._settlePromiseCtx (/Users/ac/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:606:10)
10 verbose stack     at Async._drainQueue (/Users/ac/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
10 verbose stack     at Async._drainQueues (/Users/ac/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
10 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/Users/ac/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
11 verbose cwd /Users/ac/maka/maka-cdn
12 verbose Darwin 18.6.0
13 verbose argv "/Users/ac/.nvm/versions/node/v10.15.3/bin/node" "/Users/ac/.nvm/versions/node/v10.15.3/bin/npm" "install" "-g" "--prefix" "/Users/ac/obito" "@sentry/browser-5.7.0@npm:@sentry/browser@5.7.0"
14 verbose node v10.15.3
15 verbose npm  v6.4.1
16 error Invalid dependency type requested: alias
17 verbose exit [ 1, true ]
```

**Comment by Alex1990** [comment]
You should use npm >= 6.9.0 because of the npm alias feature. I will add a note in readme.

**Comment by Inchill** [comment]
I met the same issue too, and I did not use alias, I'm confused about where it could be used in my project.

**Comment by Alex1990** [comment]
The alias is used in https://github.com/Alex1990/obito/blob/master/bin/obito-sync#L40.
